name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
      - name: Compile CLI
        run: go build
      - name: Test CLI
        run: |
          go test -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
      - name: Create Tag for Release
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: github.ref != 'ref/heads/main'
          WITH_V: true
